//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class PaymentIndentList {
    
    /// <summary>
    /// ToolkitScriptManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.ToolkitScriptManager ToolkitScriptManager1;
    
    /// <summary>
    /// Grid_PaymentIndent control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Obout.Grid.Grid Grid_PaymentIndent;
    
    /// <summary>
    /// PayIndNoTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Obout.Grid.GridTemplate PayIndNoTemplate;
    
    /// <summary>
    /// lnkbtnAdd control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkbtnAdd;
    
    /// <summary>
    /// lnkbtnBank control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkbtnBank;
    
    /// <summary>
    /// btnExportToPDF control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button btnExportToPDF;
    
    /// <summary>
    /// GridPendingBalance control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Obout.Grid.Grid GridPendingBalance;
    
    /// <summary>
    /// PayIndNoTemplatePartialBalance control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Obout.Grid.GridTemplate PayIndNoTemplatePartialBalance;
    
    /// <summary>
    /// btnPendingPartialGrid control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button btnPendingPartialGrid;
    
    /// <summary>
    /// Grid_PaymentIndent_Approved control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Obout.Grid.Grid Grid_PaymentIndent_Approved;
    
    /// <summary>
    /// PayIndNoTemplateApproved control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Obout.Grid.GridTemplate PayIndNoTemplateApproved;
    
    /// <summary>
    /// btnExportToPDF_Approved control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button btnExportToPDF_Approved;
    
    /// <summary>
    /// Grid_PaymentIndent_Completed control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Obout.Grid.Grid Grid_PaymentIndent_Completed;
    
    /// <summary>
    /// EditTransAmtTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Obout.Grid.GridTemplate EditTransAmtTemplate;
    
    /// <summary>
    /// EditCompany_BankTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Obout.Grid.GridTemplate EditCompany_BankTemplate;
    
    /// <summary>
    /// EditPaymentDateTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Obout.Grid.GridTemplate EditPaymentDateTemplate;
    
    /// <summary>
    /// EditPaymentRefNoTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Obout.Grid.GridTemplate EditPaymentRefNoTemplate;
    
    /// <summary>
    /// EditNarrationTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Obout.Grid.GridTemplate EditNarrationTemplate;
    
    /// <summary>
    /// SelectTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Obout.Grid.GridTemplate SelectTemplate;
    
    /// <summary>
    /// SelectTemplatePAYIND control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Obout.Grid.GridTemplate SelectTemplatePAYIND;
    
    /// <summary>
    /// PayIndNoTemplate_Completed control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Obout.Grid.GridTemplate PayIndNoTemplate_Completed;
    
    /// <summary>
    /// lnkDownloadDocumentTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Obout.Grid.GridTemplate lnkDownloadDocumentTemplate;
    
    /// <summary>
    /// Balance_Amount control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Obout.Grid.GridTemplate Balance_Amount;
    
    /// <summary>
    /// btnReturned control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button btnReturned;
    
    /// <summary>
    /// btnExportToPDF_Completed control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button btnExportToPDF_Completed;
    
    /// <summary>
    /// btnNewPAYIND control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button btnNewPAYIND;
    
    /// <summary>
    /// GridBankingIndent control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Obout.Grid.Grid GridBankingIndent;
    
    /// <summary>
    /// BANK_INDENT_NoTemplate_Completed control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Obout.Grid.GridTemplate BANK_INDENT_NoTemplate_Completed;
    
    /// <summary>
    /// btnAddSubItem control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button btnAddSubItem;
    
    /// <summary>
    /// ModalWOSubItem control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AjaxControlToolkit.ModalPopupExtender ModalWOSubItem;
    
    /// <summary>
    /// PanelWOSubItem control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel PanelWOSubItem;
    
    /// <summary>
    /// lblPendingGrid_DocDownload control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblPendingGrid_DocDownload;
    
    /// <summary>
    /// Grid_File control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Obout.Grid.Grid Grid_File;
    
    /// <summary>
    /// FileTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Obout.Grid.GridTemplate FileTemplate;
    
    /// <summary>
    /// DDLCompanyBanks control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.SqlDataSource DDLCompanyBanks;
}
